//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_DOCUMENTPROFILES
    {
        public int DOCID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public Nullable<int> DOCTYPEID { get; set; }
        public Nullable<int> DOCSUBTYPEID { get; set; }
        public string REFERENCENO { get; set; }
        public string DOCTITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ISSUEDATE { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public Nullable<int> ISSUEDBYID { get; set; }
        public Nullable<int> ISSUEDCOUNTRYID { get; set; }
        public Nullable<bool> NEEDTOVERIFY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDON { get; set; }
    
        public virtual DMN_MEMBERS DMN_MEMBERS { get; set; }
        public virtual DMN_DOCUMENTS DMN_DOCUMENTS { get; set; }
        public virtual DMN_VERIFYINFO DMN_VERIFYINFO { get; set; }
    }
}
