//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_AUDITLOG
    {
        public int AUDITID { get; set; }
        public string AUDITCODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string WORKSTATIONNAME { get; set; }
        public string NETWORKIP { get; set; }
        public string SOURCE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
    }
}
