//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_PAYMENTDETAILS
    {
        public int PAYMENTID { get; set; }
        public int SUBSCRIPTIONID { get; set; }
        public Nullable<int> PAYMENTMODE { get; set; }
        public Nullable<decimal> PAIDAMOUNT { get; set; }
        public Nullable<System.DateTime> EXPIRYDATE { get; set; }
        public string TRANSACTIONREF { get; set; }
    
        public virtual DMN_SUBSCRIPTIONS DMN_SUBSCRIPTIONS { get; set; }
    }
}
