//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_MEMBERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_MEMBERS()
        {
            this.DMN_CALENDARITEMS = new HashSet<DMN_CALENDARITEMS>();
            this.DMN_DOCUMENTPROFILES = new HashSet<DMN_DOCUMENTPROFILES>();
            this.DMN_EDUCATION = new HashSet<DMN_EDUCATION>();
            this.DMN_MEMBERSOCIALIDS = new HashSet<DMN_MEMBERSOCIALIDS>();
            this.DMN_MEMBERVESSELS = new HashSet<DMN_MEMBERVESSELS>();
            this.DMN_NEXTOFKIN = new HashSet<DMN_NEXTOFKIN>();
            this.DMN_SEAASSIGNMENTS = new HashSet<DMN_SEAASSIGNMENTS>();
            this.DMN_WORKASSIGNMENTS = new HashSet<DMN_WORKASSIGNMENTS>();
            this.DMN_CORPORATES = new HashSet<DMN_CORPORATES>();
        }
    
        public int MEMBERID { get; set; }
        public string REFERENCE { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<System.DateTime> STATUSDATE { get; set; }
        public Nullable<bool> PRIVATE { get; set; }
        public Nullable<System.DateTime> LASTLOGGEDIN { get; set; }
        public Nullable<System.DateTime> LASTPASSWORDCHANGED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_CALENDARITEMS> DMN_CALENDARITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_DOCUMENTPROFILES> DMN_DOCUMENTPROFILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_EDUCATION> DMN_EDUCATION { get; set; }
        public virtual DMN_MEMBERPROFILE DMN_MEMBERPROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_MEMBERSOCIALIDS> DMN_MEMBERSOCIALIDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_MEMBERVESSELS> DMN_MEMBERVESSELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_NEXTOFKIN> DMN_NEXTOFKIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_SEAASSIGNMENTS> DMN_SEAASSIGNMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_WORKASSIGNMENTS> DMN_WORKASSIGNMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_CORPORATES> DMN_CORPORATES { get; set; }
    }
}
