//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_CORPORATES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_CORPORATES()
        {
            this.DMN_CORPORATESERVICEPROVIDERS = new HashSet<DMN_CORPORATESERVICEPROVIDERS>();
            this.DMN_CORPORATEUSERS = new HashSet<DMN_CORPORATEUSERS>();
            this.DMN_CORPORATEVESSELS = new HashSet<DMN_CORPORATEVESSELS>();
            this.DMN_MEMBERS = new HashSet<DMN_MEMBERS>();
        }
    
        public int CORPORATEID { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<int> SUBSCRIPTIONID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
    
        public virtual DMN_CORPORATEPROFILE DMN_CORPORATEPROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_CORPORATESERVICEPROVIDERS> DMN_CORPORATESERVICEPROVIDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_CORPORATEUSERS> DMN_CORPORATEUSERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_CORPORATEVESSELS> DMN_CORPORATEVESSELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_MEMBERS> DMN_MEMBERS { get; set; }
    }
}
