//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_VERIFYINFO
    {
        public int DOCID { get; set; }
        public Nullable<int> SERVICEPROVIDERID { get; set; }
        public Nullable<System.DateTime> REQUESTDATE { get; set; }
        public Nullable<System.DateTime> SUBMITTEDDATE { get; set; }
        public string SUBMITTEDEMAIL { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REPLYDATE { get; set; }
        public string REPLYRESULT { get; set; }
        public Nullable<int> REPLYDOCID { get; set; }
    
        public virtual DMN_DOCUMENTPROFILES DMN_DOCUMENTPROFILES { get; set; }
    }
}
