//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_VESSELS
    {
        public int VESSELID { get; set; }
        public int VESSELCATEGORY { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> GROSSTONNAGE { get; set; }
        public Nullable<decimal> CAPACITY { get; set; }
        public string VESSELTYPE { get; set; }
        public string FLAG { get; set; }
        public string CALLSIGN { get; set; }
        public string IMONUMBER { get; set; }
        public Nullable<decimal> TEU { get; set; }
        public Nullable<decimal> ENGINEPOWER { get; set; }
        public string ENGINETYPE { get; set; }
        public string VESSELOWNER { get; set; }
        public string REGISTEREDCOMPANY { get; set; }
        public string PORTOFREGISTRY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDON { get; set; }
        public string LASTMODIFIEDBY { get; set; }
    }
}
