//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_SUBSCRIPTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_SUBSCRIPTIONS()
        {
            this.DMN_PAYMENTDETAILS = new HashSet<DMN_PAYMENTDETAILS>();
        }
    
        public int SUBSCRIPTIONID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public Nullable<int> PLANID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_PAYMENTDETAILS> DMN_PAYMENTDETAILS { get; set; }
        public virtual DMN_PLANMASTER DMN_PLANMASTER { get; set; }
    }
}
