//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_MEMBERPROFILE
    {
        public int MEMBERID { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string FULLNAME { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<int> GENDERID { get; set; }
        public Nullable<int> CITIZENSHIPID { get; set; }
        public Nullable<int> MARITALSTATUSID { get; set; }
        public string RESIDENTADDRESS1 { get; set; }
        public string RESIDENTADDRESS2 { get; set; }
        public string RESIDENTADDRESS3 { get; set; }
        public string RESIDENTCITY { get; set; }
        public Nullable<int> RESIDENTCOUNTRYID { get; set; }
        public string RESIDENTZIPCODE { get; set; }
        public string PRIMARYCONTACT { get; set; }
        public string SECONDARYCONTACT { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public byte[] PHOTO { get; set; }
        public string LANGUAGES { get; set; }
        public Nullable<int> SOURCEID { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDON { get; set; }
        public string LASTMODIFIEDBY { get; set; }
    
        public virtual DMN_MEMBERS DMN_MEMBERS { get; set; }
    }
}
