//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_VERIFICATIONPLANS
    {
        public int PURCHASEID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public Nullable<int> PAYMENTMODE { get; set; }
        public Nullable<decimal> PAIDAMOUNT { get; set; }
    }
}
