//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_CORPORATEUSERS
    {
        public int CORPORATEID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FULLNAME { get; set; }
        public byte[] PHOTO { get; set; }
        public string DESIGNATION { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAILADDRESS { get; set; }
        public string PERMISSION { get; set; }
        public Nullable<System.DateTime> LASTLOGGEDIN { get; set; }
        public string STATUS { get; set; }
    
        public virtual DMN_CORPORATES DMN_CORPORATES { get; set; }
    }
}
