//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_EDUCATION
    {
        public int EDUCATIONID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public string EDUCATIONLEVEL { get; set; }
        public string INSTITUTION { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string SPECIALIZATION { get; set; }
    
        public virtual DMN_MEMBERS DMN_MEMBERS { get; set; }
    }
}
