//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_REMINDERITEMS
    {
        public int REMINDERID { get; set; }
        public int CALENDARITEMID { get; set; }
        public string REMINDERUSERID { get; set; }
        public string REMINDERTYPE { get; set; }
        public Nullable<int> FREQUENCYDAYS { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public string STATUS { get; set; }
    }
}
