//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_CORPORATEVESSELS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_CORPORATEVESSELS()
        {
            this.DMN_PASSAGES = new HashSet<DMN_PASSAGES>();
        }
    
        public int VESSELID { get; set; }
        public int CORPORATEID { get; set; }
    
        public virtual DMN_CORPORATES DMN_CORPORATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_PASSAGES> DMN_PASSAGES { get; set; }
    }
}
