//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_FISHINGLIST
    {
        public int EMPLOYERID { get; set; }
        public int MEMBERID { get; set; }
        public Nullable<System.DateTime> SHORTLISTEDDATE { get; set; }
        public Nullable<bool> DOWNLOADED { get; set; }
        public Nullable<System.DateTime> DOWNLOADDATE { get; set; }
    
        public virtual DMN_EMPLOYERS DMN_EMPLOYERS { get; set; }
    }
}
