//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_JOBADVERTISEMENT
    {
        public int ADVERTISEID { get; set; }
        public Nullable<int> JOBID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> STATUSID { get; set; }
        public Nullable<int> READCOUNT { get; set; }
        public Nullable<int> MEMBERAPPLYCOUNT { get; set; }
        public Nullable<int> NONMEMBERAPPLYCOUNT { get; set; }
    
        public virtual DMN_JOBPOSTING DMN_JOBPOSTING { get; set; }
    }
}
