//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_MEMBERSOCIALIDS
    {
        public int SOCIALID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public string SOCIALNETWORK { get; set; }
        public string SOCIALNETWORKID { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    
        public virtual DMN_MEMBERS DMN_MEMBERS { get; set; }
    }
}
