//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_PLANMASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_PLANMASTER()
        {
            this.DMN_SUBSCRIPTIONS = new HashSet<DMN_SUBSCRIPTIONS>();
        }
    
        public int PLANID { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> CURRENCY { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<int> STORAGE { get; set; }
        public Nullable<int> DOCUMENTS { get; set; }
        public Nullable<int> REMINDERS { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string REMARKS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_SUBSCRIPTIONS> DMN_SUBSCRIPTIONS { get; set; }
    }
}
