//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_SYSCONFIG
    {
        public string SECTION { get; set; }
        public string KEYNAME { get; set; }
        public string KEYNAME2 { get; set; }
        public string KEYVALUE { get; set; }
        public string KEYVALUEXEX { get; set; }
    }
}
