//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_LOOKUPS
    {
        public int LOOKUPID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public Nullable<int> PARENTID { get; set; }
        public string VALUE { get; set; }
    
        public virtual DMN_LOOKUPCATEGORIES DMN_LOOKUPCATEGORIES { get; set; }
    }
}
