//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_DOCUMENTS
    {
        public int DOCID { get; set; }
        public Nullable<int> DOCTYPEID { get; set; }
        public Nullable<int> LINKID { get; set; }
        public string DOCSOURCE { get; set; }
        public Nullable<System.Guid> FILEUI { get; set; }
        public string FILENAME { get; set; }
        public string FILEEXTENSION { get; set; }
        public Nullable<int> FILESIZE { get; set; }
        public byte[] FILEPATH { get; set; }
        public Nullable<bool> PRIVATE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
    
        public virtual DMN_DOCUMENTPROFILES DMN_DOCUMENTPROFILES { get; set; }
    }
}
