//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_JOBPOSTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMN_JOBPOSTING()
        {
            this.DMN_JOBADVERTISEMENT = new HashSet<DMN_JOBADVERTISEMENT>();
            this.DMN_JOBAPPLICANTS = new HashSet<DMN_JOBAPPLICANTS>();
        }
    
        public int JOBID { get; set; }
        public Nullable<int> EMPLOYERID { get; set; }
        public string JOBTITLE { get; set; }
        public string REFERENCE { get; set; }
        public string JOBOWNER { get; set; }
        public Nullable<int> JOBTYPEID { get; set; }
        public Nullable<int> JOBLOCATIONID { get; set; }
        public Nullable<int> JOBSUBLOCATIONID { get; set; }
        public Nullable<int> VACANCIES { get; set; }
        public Nullable<int> SPECIALIZATIONID { get; set; }
        public Nullable<int> SUBSPECIALIZATIONID { get; set; }
        public Nullable<int> MINQUALIFICATIONID { get; set; }
        public Nullable<int> MINSEAEXPERIENCE { get; set; }
        public Nullable<int> MINWORKEXPERIENCE { get; set; }
        public Nullable<decimal> MINSALARY { get; set; }
        public Nullable<decimal> MAXSALARY { get; set; }
        public Nullable<int> CURRENCYID { get; set; }
        public string SALARYDESCRIPTION { get; set; }
        public string REMARKS { get; set; }
        public byte[] JOBDESCRIPTION { get; set; }
    
        public virtual DMN_EMPLOYERS DMN_EMPLOYERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_JOBADVERTISEMENT> DMN_JOBADVERTISEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMN_JOBAPPLICANTS> DMN_JOBAPPLICANTS { get; set; }
    }
}
