//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_WORKASSIGNMENTS
    {
        public int ASSIGNEMENTID { get; set; }
        public Nullable<int> MEMBERID { get; set; }
        public string COMPANY { get; set; }
        public string TITLE { get; set; }
        public Nullable<int> DEPARTMENTID { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string LOCATION { get; set; }
        public Nullable<bool> PRIVATE { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDON { get; set; }
        public string LASTMODIFIEDBY { get; set; }
    
        public virtual DMN_MEMBERS DMN_MEMBERS { get; set; }
    }
}
