//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_EMPLOYERPROFILE
    {
        public int EMPLOYERID { get; set; }
        public string FULLNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<int> COREINDUSTRYID { get; set; }
        public Nullable<int> LOCATIONID { get; set; }
        public string REGNNO { get; set; }
        public string WEBSITE { get; set; }
        public string TELEPHONE { get; set; }
    
        public virtual DMN_EMPLOYERS DMN_EMPLOYERS { get; set; }
    }
}
