//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMN_CORPORATESERVICEPROVIDERS
    {
        public int CORPORATEID { get; set; }
        public int SERVICEPROVIDERID { get; set; }
    
        public virtual DMN_CORPORATES DMN_CORPORATES { get; set; }
    }
}
