//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBAR.AccessDataLayer.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PBAR_PORTALEntities : DbContext
    {
        public PBAR_PORTALEntities()
            : base("name=PBAR_PORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMN_AUDITLOG> DMN_AUDITLOG { get; set; }
        public virtual DbSet<DMN_CALENDARITEMS> DMN_CALENDARITEMS { get; set; }
        public virtual DbSet<DMN_CORPORATEPROFILE> DMN_CORPORATEPROFILE { get; set; }
        public virtual DbSet<DMN_CORPORATES> DMN_CORPORATES { get; set; }
        public virtual DbSet<DMN_CORPORATESERVICEPROVIDERS> DMN_CORPORATESERVICEPROVIDERS { get; set; }
        public virtual DbSet<DMN_CORPORATEUSERS> DMN_CORPORATEUSERS { get; set; }
        public virtual DbSet<DMN_CORPORATEVESSELS> DMN_CORPORATEVESSELS { get; set; }
        public virtual DbSet<DMN_CREWLIST> DMN_CREWLIST { get; set; }
        public virtual DbSet<DMN_DOCUMENTPROFILES> DMN_DOCUMENTPROFILES { get; set; }
        public virtual DbSet<DMN_DOCUMENTS> DMN_DOCUMENTS { get; set; }
        public virtual DbSet<DMN_EDUCATION> DMN_EDUCATION { get; set; }
        public virtual DbSet<DMN_EMPLOYERPROFILE> DMN_EMPLOYERPROFILE { get; set; }
        public virtual DbSet<DMN_EMPLOYERS> DMN_EMPLOYERS { get; set; }
        public virtual DbSet<DMN_FISHINGLIST> DMN_FISHINGLIST { get; set; }
        public virtual DbSet<DMN_JOBADVERTISEMENT> DMN_JOBADVERTISEMENT { get; set; }
        public virtual DbSet<DMN_JOBAPPLICANTS> DMN_JOBAPPLICANTS { get; set; }
        public virtual DbSet<DMN_JOBPOSTING> DMN_JOBPOSTING { get; set; }
        public virtual DbSet<DMN_LOOKUPCATEGORIES> DMN_LOOKUPCATEGORIES { get; set; }
        public virtual DbSet<DMN_LOOKUPS> DMN_LOOKUPS { get; set; }
        public virtual DbSet<DMN_MEMBERCONFIRMATIONEMAIL> DMN_MEMBERCONFIRMATIONEMAIL { get; set; }
        public virtual DbSet<DMN_MEMBERPROFILE> DMN_MEMBERPROFILE { get; set; }
        public virtual DbSet<DMN_MEMBERS> DMN_MEMBERS { get; set; }
        public virtual DbSet<DMN_MEMBERSOCIALIDS> DMN_MEMBERSOCIALIDS { get; set; }
        public virtual DbSet<DMN_MEMBERVESSELS> DMN_MEMBERVESSELS { get; set; }
        public virtual DbSet<DMN_NEXTOFKIN> DMN_NEXTOFKIN { get; set; }
        public virtual DbSet<DMN_PASSAGEACCESS> DMN_PASSAGEACCESS { get; set; }
        public virtual DbSet<DMN_PASSAGES> DMN_PASSAGES { get; set; }
        public virtual DbSet<DMN_PAYMENTDETAILS> DMN_PAYMENTDETAILS { get; set; }
        public virtual DbSet<DMN_PLANMASTER> DMN_PLANMASTER { get; set; }
        public virtual DbSet<DMN_REMINDERITEMS> DMN_REMINDERITEMS { get; set; }
        public virtual DbSet<DMN_ROTATIONALSEAASSIGNMENTS> DMN_ROTATIONALSEAASSIGNMENTS { get; set; }
        public virtual DbSet<DMN_SEAASSIGNMENTS> DMN_SEAASSIGNMENTS { get; set; }
        public virtual DbSet<DMN_SERVICEPROVIDERS> DMN_SERVICEPROVIDERS { get; set; }
        public virtual DbSet<DMN_SUBSCRIPTIONS> DMN_SUBSCRIPTIONS { get; set; }
        public virtual DbSet<DMN_SYSCONFIG> DMN_SYSCONFIG { get; set; }
        public virtual DbSet<DMN_VERIFICATIONPLANS> DMN_VERIFICATIONPLANS { get; set; }
        public virtual DbSet<DMN_VERIFYINFO> DMN_VERIFYINFO { get; set; }
        public virtual DbSet<DMN_VESSELS> DMN_VESSELS { get; set; }
        public virtual DbSet<DMN_WORKASSIGNMENTS> DMN_WORKASSIGNMENTS { get; set; }
    
        public virtual int SearchTFF(string tblname, string fldname, string fldvalue)
        {
            var tblnameParameter = tblname != null ?
                new ObjectParameter("tblname", tblname) :
                new ObjectParameter("tblname", typeof(string));
    
            var fldnameParameter = fldname != null ?
                new ObjectParameter("fldname", fldname) :
                new ObjectParameter("fldname", typeof(string));
    
            var fldvalueParameter = fldvalue != null ?
                new ObjectParameter("fldvalue", fldvalue) :
                new ObjectParameter("fldvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchTFF", tblnameParameter, fldnameParameter, fldvalueParameter);
        }
    }
}
